CREATE OR REPLACE FILE FORMAT WEATHER_DB_VM.RAW_WEATHER_VM.WEATHER_FILE_FORMAT
  TYPE=CSV,
  SKIP_HEADER=1,
  TRIM_SPACE=FALSE,
  FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
  REPLACE_INVALID_CHARACTERS=TRUE,
  DATE_FORMAT="YYYY-MM-DD",
  TIME_FORMAT="YYYY-MM-DD HH24:MI",
  TIMESTAMP_FORMAT="YYYY-MM-DD HH24:MI";