CREATE OR REPLACE TASK WEATHER_DB_VM.DM_WEATHER_VM.DM_LOCATION_DTL_TASK
  SCHEDULE = '1 MINUTE'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  SUSPEND_TASK_AFTER_NUM_FAILURES = 2 
  --[ ERROR_INTEGRATION = <integration_name> ]
  --[ COPY GRANTS ]
  --[ COMMENT = '<string_literal>' ]
  --[ AFTER <string> [ , <string> , ... ] ]  
 WHEN SYSTEM$STREAM_HAS_DATA('WEATHER_DB_VM.RAW_WEATHER_VM.RAW_LOCATION_DTL_STREAM')
AS
  CALL WEATHER_DB_VM.DM_WEATHER_VM.SP_SIL_DM_LOCATION_DTL();