CREATE OR REPLACE TASK WEATHER_DB_VM.DM_WEATHER_VM.DM_LATEST_WEATHER_DTL_TASK
  AFTER WEATHER_DB_VM.DM_WEATHER_VM.DM_WEATHER_DTL_TASK,WEATHER_DB_VM.DM_WEATHER_VM.DM_CURRENT_CONDITION_DTL_TASK
AS
  CALL WEATHER_DB_VM.DM_WEATHER_VM.SP_PLP_DM_LATEST_WEATHER_DTL();
  