EXECUTE TASK WEATHER_DB_VM.DM_WEATHER_VM.DM_WEATHER_DTL_TASK;

EXECUTE TASK WEATHER_DB_VM.DM_WEATHER_VM.DM_CURRENT_CONDITION_DTL_TASK;


SELECT DISTINCT WEATHER_TIME FROM WEATHER_DB_VM.DM_WEATHER_VM.DM_LATEST_WEATHER_DTL --WHERE WEATHER_TIME>'2023-11-26'
ORDER BY WEATHER_TIME;


SELECT DISTINCT LAST_UPDATED FROM WEATHER_DB_VM.DM_WEATHER_VM.DM_WEATHER_DTL WHERE DATE(LAST_UPDATED)='2023-11-28'
ORDER BY LAST_UPDATED;

select * from DM_WEATHER_VM.DM_LATEST_WEATHER_DTL where date(weather_time)='2023-11-28' AND CITY='Madurai';

select * from DM_WEATHER_VM.DM_CURRENT_CONDITION_DTL where date(WEATHER_TIME)='2023-11-28'
ORDER BY CITY;

