create or replace TABLE WEATHER_DB_VM.DM_WEATHER_VM.DM_LATEST_WEATHER_DTL (
	INTEGRATION_ID VARCHAR(16777216),
	CITY VARCHAR(100),
	TEMP_C FLOAT,
	CLOUD FLOAT,
	TEXT VARCHAR(100),
	ICON VARCHAR(500),
	WEATHER_TIME TIMESTAMP_NTZ(9),
	CITY_LOCATION GEOGRAPHY,
	CITY_LOCALTIME TIMESTAMP_NTZ(9),
	EFFECTIVE_FROM_DATE TIMESTAMP_NTZ(9),
	EFFECTIVE_TO_DATE VARCHAR(16777216),
	ACTIVE_REC_FLAG VARCHAR(1),
	TGT_INSERT_DT TIMESTAMP_LTZ(9),
	TGT_UPDATE_DT TIMESTAMP_LTZ(9)
);