create table if not exists WEATHER_DB_VM.DM_WEATHER_VM.DM_WEATHER_DTL
(
integration_id VARCHAR(200),
last_updated_epoch NUMBER,
last_updated DATETIME,
city VARCHAR(100),
temp_c FLOAT,
temp_f FLOAT,
is_day FLOAT,
wind_mph FLOAT,
wind_kph FLOAT,
wind_degree FLOAT,
wind_dir VARCHAR(10),
pressure_mb FLOAT,
pressure_in FLOAT,
precip_mm FLOAT,
precip_in FLOAT,
humidity FLOAT,
cloud FLOAT,
feelslike_c FLOAT,
feelslike_f FLOAT,
vis_km FLOAT,
vis_miles FLOAT,
uv FLOAT,
gust_mph FLOAT,
gust_kph FLOAT,
TGT_INSERT_DT DATETIME,
TGT_UPDATE_DT DATETIME,
CONSTRAINT pk_weather_dtl primary key (integration_id)
);