create table if not exists WEATHER_DB_VM.RAW_WEATHER_VM.RAW_WEATHER_DTL
(
filename varchar,
file_row_number int,
file_content_key varchar,
file_last_modified timestamp_ntz,
start_scan_time timestamp_ltz,
last_updated_epoch NUMBER,
last_updated DATETIME,
temp_c FLOAT,
temp_f FLOAT,
is_day FLOAT,
wind_mph FLOAT,
wind_kph FLOAT,
wind_degree FLOAT,
wind_dir VARCHAR(10),
pressure_mb FLOAT,
pressure_in FLOAT,
precip_mm FLOAT,
precip_in FLOAT,
humidity FLOAT,
cloud FLOAT,
feelslike_c FLOAT,
feelslike_f FLOAT,
vis_km FLOAT,
vis_miles FLOAT,
uv FLOAT,
gust_mph FLOAT,
gust_kph FLOAT,
city VARCHAR(100)
);